import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const systemPrompt = readFileSync('docs/product/PROMPT-OPINION-SYSTEM-PROMPT.md', 'utf8');
const byoConfig = readFileSync('docs/product/PROMPT-OPINION-BYO-AGENT-CONFIG.md', 'utf8');
const chatTestPrompt = readFileSync('docs/product/PROMPT-OPINION-CHAT-TEST-PROMPT.md', 'utf8');

assert.match(systemPrompt, /Prompt Opinion Patient\/Data Scope/);
assert.match(systemPrompt, /FHIR-style chart data/);
assert.doesNotMatch(systemPrompt, /GetPatientData\(resourceType/);
assert.match(systemPrompt, /Do not call or request `FindPatientId`/);
assert.match(systemPrompt, /Do not retry failed patient lookup tools/);
assert.match(systemPrompt, /PDMP_PRESCRIPTION_HISTORY_OVERLAY/);
assert.match(systemPrompt, /PO_PATIENT_TAMERA_WISOZK/);
assert.match(systemPrompt, /PO_PATIENT_LINCOLN_BEDNAR/);
assert.match(systemPrompt, /PO_PATIENT_GROVER_KEELING/);
assert.match(systemPrompt, /Overlay names must not encode risk level/);
assert.match(systemPrompt, /Alprazolam 1 mg/);
assert.match(systemPrompt, /Oxycodone 10 mg/);
assert.match(systemPrompt, /native_patient_context_status/);
assert.match(systemPrompt, /Do NOT output PDMP table rows/);
assert.match(systemPrompt, /Do NOT include a pdmp_summary array/);
assert.match(systemPrompt, /PDMP review not charted/);
assert.match(systemPrompt, /Output JSON ONLY/);
assert.doesNotMatch(systemPrompt, /PDMP_DATABASE/);
assert.match(systemPrompt, /Tamera164 Wisozk929/);
assert.match(systemPrompt, /Lincoln623 Bednar518/);
assert.match(systemPrompt, /Grover Keeling/);
assert.doesNotMatch(systemPrompt, /HIGH_RISK|MODERATE_RISK|LOW_RISK/);
assert.doesNotMatch(systemPrompt, /call the RXGuard MCP tools/i);
assert.doesNotMatch(systemPrompt, /MCP is the only source/i);
assert.doesNotMatch(systemPrompt, /lookup_patient_medication_context/);

assert.match(byoConfig, /native FHIR-style patient context/);
assert.match(byoConfig, /PDMP_PRESCRIPTION_HISTORY_OVERLAY/);
assert.match(byoConfig, /do not attach RXGuard MCP/i);
assert.match(byoConfig, /Do not rely on patient search or patient-ID lookup/);
assert.match(byoConfig, /FindPatientId/);
assert.match(byoConfig, /selected Prompt Opinion Patient\/Data Scope context/);
assert.match(byoConfig, /native_patient_context_status/);
assert.match(byoConfig, /Controlled-Substance Safety Review/);
assert.match(byoConfig, /PDMP Documentation Gap Check/);
assert.match(byoConfig, /EHR Auto-Note Draft/);
assert.match(byoConfig, /Human-in-the-loop: never autonomous prescribing/);
assert.doesNotMatch(byoConfig, /synthetic, de-identified `PDMP_DATABASE` directly/);
assert.doesNotMatch(byoConfig, /MCP-only/i);
assert.doesNotMatch(byoConfig, /hosted RXGuard MCP server/i);
assert.doesNotMatch(byoConfig, /20 `generate_content` requests per day/);

assert.match(chatTestPrompt, /current selected Prompt Opinion Patient\/Data Scope context/);
assert.match(chatTestPrompt, /Do not call or retry FindPatientId/);
assert.match(chatTestPrompt, /PO_PATIENT_SHEILA_BANKSTON/);
assert.doesNotMatch(chatTestPrompt, /HIGH_RISK|MODERATE_RISK|LOW_RISK/);
assert.match(chatTestPrompt, /Proposed medication: Xanax 1 mg tablet/);
assert.match(chatTestPrompt, /Patient-reported history: no recent narcotic or controlled-substance use/);
assert.match(chatTestPrompt, /native_patient_context_status/);
assert.match(chatTestPrompt, /pdmp_summary_status/);
assert.match(chatTestPrompt, /Do not include PDMP table rows/);
assert.doesNotMatch(chatTestPrompt, /Synthetic patient key: RXG-SB-001/);
assert.doesNotMatch(chatTestPrompt, /MCP tools/i);
assert.doesNotMatch(chatTestPrompt, /lookup_patient_medication_context/);

console.log('prompt opinion config tests passed');
